function show(id,btn){document.querySelectorAll(".section").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".side button").forEach(x=>x.classList.remove("active"));if(btn)btn.classList.add("active")}
function loginPatient(){const p=LH.findByMobile(document.getElementById("loginMobile").value.trim());if(!p)return alert("Patient not found. Create a Health ID first.");LH.login(p.id);render()}
function createPatient(){const name=document.getElementById("newName").value.trim(),mobile=document.getElementById("newMobile").value.trim();if(!name||!mobile)return alert("Name and mobile are required.");if(LH.findByMobile(mobile))return alert("This mobile is already registered. Please log in.");const p={id:LH.nextId(),name,mobile,dob:"",gender:"",email:"",address:"",emergency:"",vitals:{},allergies:[],history:[],medicines:[],visits:[],reports:[],appointments:[],consents:[],referrals:[]};LH.savePatient(p);LH.login(p.id);render()}
function render(){const p=LH.current();if(!p){document.getElementById("login").style.display="block";document.getElementById("portal").style.display="none";return}document.getElementById("login").style.display="none";document.getElementById("portal").style.display="grid";document.getElementById("pname").textContent=p.name;document.getElementById("patientId").textContent=p.id;document.getElementById("pidValue").textContent=p.id;document.getElementById("aCount").textContent=p.appointments.length;document.getElementById("mCount").textContent=p.medicines.length;document.getElementById("rCount").textContent=p.reports.length;document.getElementById("vCount").textContent=p.visits.length;
document.getElementById("appointmentList").innerHTML=p.appointments.length?p.appointments.map(a=>`<div class="card"><b>${a.doctor}</b><p>${a.clinic} • ${a.date}</p><span class="tag">${a.status}</span></div>`).join(""):'<div class="empty">No appointments yet.</div>';
document.getElementById("medicineList").innerHTML=p.medicines.length?p.medicines.map(m=>`<div class="card"><b>${m.name}</b><p>${m.dose} • ${m.frequency} • ${m.duration}</p><span class="muted">${m.doctor} • ${m.date}</span></div>`).join(""):'<div class="empty">No prescriptions yet.</div>';
document.getElementById("reportList").innerHTML=p.reports.length?p.reports.map(r=>`<div class="card"><b>${r.test}</b><p>${r.lab} • ${r.date}</p><span class="tag">${r.status}</span></div>`).join(""):'<div class="empty">No reports yet.</div>';
document.getElementById("visitList").innerHTML=p.visits.length?p.visits.map(v=>`<div class="card"><b>${v.date} — ${v.doctor}</b><p>Reason: ${v.reason||"—"}</p><p>Diagnosis: ${v.diagnosis||"—"}</p></div>`).join(""):'<div class="empty">No visits yet.</div>';
document.getElementById("recordContent").innerHTML=`<div class="grid"><div class="card"><h3>Vitals</h3><p>BP: ${p.vitals.bp||"—"}</p><p>Pulse: ${p.vitals.pulse||"—"}</p><p>SpO₂: ${p.vitals.spo2||"—"}</p><p>Weight: ${p.vitals.weight||"—"}</p></div><div class="card"><h3>Allergies</h3><p>${p.allergies.length?p.allergies.join(", "):"None recorded"}</p></div><div class="card"><h3>Medical History</h3><p>${p.history.length?p.history.join("<br>"):"No history recorded yet."}</p></div></div>`;
document.getElementById("profileContent").innerHTML=`<div class="card"><p><b>Name:</b> ${p.name}</p><p><b>DOB:</b> ${p.dob||"—"}</p><p><b>Gender:</b> ${p.gender||"—"}</p><p><b>Mobile:</b> ${p.mobile}</p><p><b>Email:</b> ${p.email||"—"}</p><p><b>Address:</b> ${p.address||"—"}</p></div>`;
document.getElementById("consentContent").innerHTML=p.consents.length?p.consents.map(c=>`<div class="card"><b>${c.provider}</b><p>${c.scope}</p><span class="tag">${c.status}</span></div>`).join(""):'<div class="empty">No consent records yet.</div>'}
function logout(){LH.logout();window.location.href="index.html"} render();
